# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-omni" do
  name "antfly-omni"
  desc "antfly with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "3c731674653bb323240bab26bdd269ff8c6aa5ff5acc62c4b5a7e7be01391223"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "02ffec7010ff427286daa22d59826d08f89287609d5ffa52a9f14e65ca2d58f6"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "5c0524306fc96516cd7879beb58a979cb14f1f8a5a184d660aa1b76be8fbe1b8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/bin/chmod", args: ["-R", "u+rw", "#{staged_path}/lib"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured via TERMITE_BACKEND_PRIORITY env var:"
    "  export TERMITE_BACKEND_PRIORITY=onnx,xla,go"
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install antflydb/taps/antfly"
  end

  # No zap stanza required
end
