# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly" do
  name "antfly"
  desc "antfly - AntflyDB with ONNX Runtime + XLA multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "895726efe80d13a14440d83f2112b920c13401431202e3f63b0ac3e4f32e003d"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "4cb34134cc237adc6491720d6ec4db2fe9dedd8f6bdcb79582413bce49c0f5ef"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "39bf7ba363d6aab9f666569b29f0dd7508e8a2c9ad9ac897697f195f30168ad7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/bin/chmod", args: ["-R", "u+rw", "#{staged_path}/lib"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
  end

  # No zap stanza required
end
