# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly" do
  name "antfly"
  desc "antfly - AntflyDB with ONNX Runtime + XLA multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "b6d66ab290359faebfa96c625ba7b0c989e17691d3f1aa5e6d5bd416b4ed187e"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "dd63ce6700d0409833c3e7d415aa2024ec8613add642ea182a13d388d87e82df"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "f25241be96b145ecb20db583d125d6f044ea0eb942858de9f2b0b5aef5a33b2a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/bin/chmod", args: ["-R", "u+rw", "#{staged_path}/lib"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
  end

  # No zap stanza required
end
