# This file is generated by GoReleaser. Manual edits should be mirrored in .goreleaser.yaml.
class Antfly < Formula
  desc "AntflyDB with ONNX Runtime and XLA multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.1.0"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "93788f843bc6318ac9347fc95fc339f014e0584a5ae20877b2637e4f94ad2aac"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "14eb8fda19a0d87d946cdf4d3f8b5a210280446fe426a80d6c6469325cbdc6de"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "1771421e62a50f5454a7a5b6f5d4d18ea1ff924bfc442b3aa980f1f4fe822fc3"
    end
  end

  def install
    libexec.install "antfly"
    libexec.install "lib" if Dir.exist?("lib")
    bin.write_exec_script libexec/"antfly"
    bash_completion.install "completions/antfly.bash" => "antfly"
    zsh_completion.install "completions/antfly.zsh" => "_antfly"
    fish_completion.install "completions/antfly.fish"
  end

  service do
    run [opt_bin/"antfly", "--data-dir", var/"lib/antfly", "swarm"]
    keep_alive true
    working_dir var/"lib/antfly"
    log_path var/"log/antfly.log"
    error_log_path var/"log/antfly.err.log"
  end

  def post_install
    (var/"lib/antfly").mkpath
  end

  test do
    system "#{bin}/antfly", "--version"
  end
end
